### ISSUE TITLE
Add metacritic score

### ISSUE THREAD

**Issue by fensoft** [pearlxcore/PS4-PKG-Tool#13]
Hello,

I've previously done my own rename script, so i'll share my works.

I'm looking for the metacritic score via this request:
`curl -s 'https://www.metacritic.com/autosearch' -H 'X-Requested-With: XMLHttpRequest' --data-raw "search_term=$search"`

It could be a good idea to add it.

Regards,
fensoft

**Comment by ninjadude333** [comment]
amazing idea, just thought of that too,

**Comment by pearlxcore** [comment]
> 
> 
> Hello,
> 
> I've previously done my own rename script, so i'll share my works.
> 
> I'm looking for the metacritic score via this request:
> `curl -s 'https://www.metacritic.com/autosearch' -H 'X-Requested-With: XMLHttpRequest' --data-raw "search_term=$search"`
> 
> It could be a good idea to add it.
> 
> Regards,
> fensoft

Is this method still working until now?
