### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by jeremyj563** [pearlxcore/PS4-PKG-Tool#19]
Hi, I'm trying to get a local dev environment setup for this project but am having a heck of a time getting all of the dependencies in order. Mostly with classes/members missing in DarkUI and PS4_Tools. Would you be able to share a 100% complete folder that contains all current code and external libraries?

Thanks!

**Comment by pearlxcore** [comment]
I will upload the dll file and source code tomorrow.

**Comment by pearlxcore** [comment]
Just add these dll to reference and you are good to go 

https://github.com/pearlxcore/PS4-PKG-Tool/releases/download/v1.3/Dependencies.zip

**Comment by jeremyj563** [comment]
Perfect, thank you!
