### ISSUE TITLE
Nice Tool + Improvements

### ISSUE THREAD

**Issue by ohhsodead** [pearlxcore/PS4-PKG-Tool#2]
Really great work on your tool, haven't tried yet but looks very cool.

May I suggest using a [DarkUI Project](https://github.com/RobinPerris/DarkUI) to improve the ui design. Instead of creating your own dark controls this will look much better. See a few my tools have used this and they all look really smooth! 

I have a fork of that repo which includes the dgv too, plus some other useful dark controls.

**Comment by pearlxcore** [comment]
I feel like rewrite the whole program. The code is messed up. The versioning is bad.

Yeah I thought I used DarkUI in some of my projects. But afaik it doesn't have datagridview control.

**Comment by ohhsodead** [comment]
@pearlxcore the original source doesn't have the dgv control, but I have hosted a version of the same repo I found somewhere online, which includes dgv and few other controls added to it. A couple of my tools have used that project and haven't had any issues.

**Comment by pearlxcore** [comment]
I switched original datagridview to darkdatagridview but when right click on it while the program is running it seems not responding at all. Is there any property disabling right click action on the control?

**Comment by ohhsodead** [comment]
@pearlxcore have you tried using the _dgv_MouseClick()_ event to prevent the right mouse button being clicked?

Or maybe, ensure there isn't a context menu set to the control. If you are using a context menu, then set it to the datagridview rows and not the datagridview itself.

**Comment by pearlxcore** [comment]
Yes I'm using context menu and was just noticed the context menu properties on dgv. A new way to use context menu.

**Comment by pearlxcore** [comment]
Replaced all dgv in project with DarkUI dgv. Looks better. Thanks ✌🏼

**Comment by ohhsodead** [comment]
@pearlxcore Glad to know! I look forward to seeing more updates on this tool! Good job.
