### ISSUE TITLE
Error on renaming couple games 

### ISSUE THREAD

**Issue by djbubba2002** [pearlxcore/PS4-PKG-Tool#20]
if any game has game / game ,, it won't renamed has the  / ( in the title) can you fix that Please thankyou keep up the great work

**Comment by komawoyo** [comment]
Here are some example games names to help: 
.hack//G.U. Last Recode
Another World / Flashback Double Pack
D/Generation HD
Fate/Extella Link

**Comment by JPi1872** [comment]
This is valid for all illegal characters in filename: 
check this : https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
Solution: 
https://codesnippets.fesslersoft.de/remove-illegal-filename-characters/

**Comment by pearlxcore** [comment]
[This](https://stackoverflow.com/a/61448658/10400784) is the best solution i guess. Will fix this issue on the next update.

**Comment by pearlxcore** [comment]
https://github.com/pearlxcore/PS4-PKG-Tool/releases/tag/v1.4
