### ISSUE TITLE
32 bit, out of memory, enable 64 bits!!

### ISSUE THREAD

**Issue by JPi1872** [pearlxcore/PS4-PKG-Tool#24]
- After using the application with my huge collection of games, I'm getting sporadic an error message saying "out of memory" and I have to close the application or it will not run any more!!! 
- My computer has16GB of ram, this should be enough!
- I see in the task manager that the process is a 32 bits process, can you please enable the 64 bit support!

**Comment by djbubba2002** [comment]
How many games you have ? In ur huge collection?

**Comment by JPi1872** [comment]
collection of 1200 file (games + DLC + updates) - disk of 7 TB - the problem is when you switch the import folder a few time, you can see that the memory consumption is still increasing!!! With a garbage collector integrated in C# you should not have memory leaks... Strange, next time I will attach a trace log.

**Comment by djbubba2002** [comment]
I have a bigger collection its not memory..I have 1,790 games Plus updates and DLC its 23TB .. mine loads up good.. I never got a error.  Hope the coder can fix ur issues

**Comment by pearlxcore** [comment]
I will add x64 version of the tool for the next update and hopefully that will solves the problem.

**Comment by pearlxcore** [comment]
https://github.com/pearlxcore/PS4-PKG-Tool/releases/tag/v1.4

**Comment by JPi1872** [comment]
done, perfect, thx!
