### ISSUE TITLE
scaning folder recursively is not working always correctly!

### ISSUE THREAD

**Issue by JPi1872** [pearlxcore/PS4-PKG-Tool#26]
Pre requirement: 
Structure like this: 
- download
  - Game 1
  - Other things
  - Game 2

Important: I have also other sub-directories containing no games, just software.
Important I have more than 5 games stored in subdirectories...

Behaviour: 
- I checked the check box "scan folder recursively", and I select the download directory.
- I see that only one directory is loaded, the first directory. 

Problem: 
- The tools is showing only the first directory, the second contains no games, just software.

Workaround: 
- Move all games to one directory, be sure it's containing only games and it works fine!

**Comment by pearlxcore** [comment]
Not sure what caused your problem but I tested on my machine ; scan and load a folder containing 3 subfolder (separate by category theme, apps, game) with the total of 902 pkg and it work flawlessly.

![Untitled](https://user-images.githubusercontent.com/36906814/106729981-09eb6680-6649-11eb-9b5c-d4731e0224f2.png)
![Untitled](https://user-images.githubusercontent.com/36906814/106730430-5e8ee180-6649-11eb-95a2-2db71ee2579f.png)

Make sure recursive scan checkbox is ticked.

**Comment by JPi1872** [comment]
mylog file: can the issue "disk not ready" throw an exception which stop the scanning?

03/02/2021 11:06:17 : Selected directory :
03/02/2021 11:06:17 : C:\Users\Admin\Downloads
03/02/2021 11:06:17 : Creating working directory..
03/02/2021 11:06:17 : Extracting resources..
03/02/2021 11:06:18 : Checking Node.js and server module..
03/02/2021 11:06:18 : Node.js not installed.
03/02/2021 11:06:18 : Module not installed.
03/02/2021 11:06:18 : Scanning PKG..
03/02/2021 11:06:19 : Extracting PKG background music..
03/02/2021 11:06:19 : Checking hardisk free space..
03/02/2021 11:06:19 : An error occured while getting hardisk freespace : The device is not ready.

03/02/2021 11:06:19 : 2 PKG found.
03/02/2021 11:06:19 : Loading PKG done.

**Comment by JPi1872** [comment]
Know I found the issue, the bug is that one package in the directory seems to be invalid, when you remove this, it works fine... I suppose this will throw an exception and stop the scanning...
[Store-R2.zip](https://github.com/pearlxcore/PS4-PKG-Tool/files/5918557/Store-R2.zip)
