### ISSUE TITLE
Strange behavior when sorting by size...

### ISSUE THREAD

**Issue by hosamn** [pearlxcore/PS4-PKG-Tool#29]
![](https://cdn-102.anonfiles.com/F1Zaj4Jap9/d6342d5b-1613474768/Capture.JPG)

**Comment by dyerseve** [comment]
It seems size is treated as a string, so when sorted it just goes 1,2,3,4 rather than sorting based on numerical sizes.

**Comment by pearlxcore** [comment]
fixed in v1.5
