### ISSUE TITLE
Please help Extracting PKG

### ISSUE THREAD

**Issue by Nichenstein** [pearlxcore/PS4-PKG-Tool#3]
Extracting PKG never works, the extracting pkg window pops up but nothing happens
Down left the green bar works and says Extracting PKG...
No disk usage using task manager for the app

**Comment by pearlxcore** [comment]
The extract pkg is broken. I disable it for temporary on the latest version until solved.

https://github.com/pearlxcore/PS4-PKG-Tool/releases/tag/v1.0
