### ISSUE TITLE
Allow rename process to move files into folders

### ISSUE THREAD

**Issue by FrankEBailey** [pearlxcore/PS4-PKG-Tool#32]
Is it possible to get the function to set different folders for base PKGs, updates, backport fixes/patches and DLC? Having all the content in a single folder feels chaotic to me.

**Comment by pearlxcore** [comment]
Nice idea. But afaik there is no way to determine a PKG is backported so the program will separate PKG to each category (base, update and addon PKG). 

This will available in the next update.
