### ISSUE TITLE
Enhancement - Group packages and compare

### ISSUE THREAD

**Issue by Viper911** [pearlxcore/PS4-PKG-Tool#36]
I wouldn't mind taking a crack at making this update if you could tell me how to set up the dev environment for a fork. What pakages, etc you used.  For example cant find a good version of the dark theme you used.

In any case, was looking for something like what Switch Backup Manager does.  Whereby it will group the game together and show the game, updates and DLCs in one, figure out what goes together and let you view and install them at once.  Also on the main screen if you could compare all the local files with the PS4 so you know what games you have installed, what updates/DLCs you may not have installed, etc.

As noted, looks like its been a while sense the last update and maybe not in active development anymore, but if you could tell me what your dev setup looked like I could take a shot at updating this.

**Comment by pearlxcore** [comment]
This will require overhaul on the program as it is currently using datagridview control. No grouping supported unlike listview control. That is why I included pkg filtering on left below of the program. Yes it is possible but it may need some time to implement it.

I may be wrong but for pkg comparison between local and server, iirc there is no way to list out installed pkg on the ps4 remotely unless you manually check the game is installed or not (using flatz remote pkg installer). Or is there any way to do it? 

Also I don't have jailbroken PS4 at the moment so developing things relating remote ps4 stuff is impossible now. Sigh.

**Comment by quarkpower** [comment]
Hello
If grouping isn't possible, is it possible to set colors for each kind? and when sort by cusa to order them (1st game, 2nd patches, 3rd dlcs)?

**Comment by pearlxcore** [comment]
> Hello If grouping isn't possible, is it possible to set colors for each kind (game, patch, dlc...)? and when sort by cusa to order them (1st game, 2nd patches, 3rd dlcs)? adding firmware requisite as a naming label would help too.
For latest v1, pkg category color label is added
