### ISSUE TITLE
App ignores any files stored on network or mapped drives

### ISSUE THREAD

**Issue by Masamune3210** [pearlxcore/PS4-PKG-Tool#38]
App works perfectly for local files, but completely ignores any files stored on network drives, even if mapped to a drive letter. I upload stuff to my server and then use rclone to mount the folder locally as a drive letter onto my computer so this kinda puts a dent in using the program. Could network drive support be added? 

It seems the support is kinda there but something is wrong, as the folder picker sees the drive letter and successfully gets added to the list but anytime the program tries to access the drive it just sees no pkgs, also the path is weird, starting with /Device instead of a drive letter like normal

**Comment by pearlxcore** [comment]
Hmm I never use mapped drive but I created new mapped drive and put some pkgs in it. Load the directory with this tool and pkg detected. Or is it different with your problem?

![image](https://user-images.githubusercontent.com/36906814/149687998-0f2a8667-104d-451f-bebe-572b69780f24.png)

**Comment by Masamune3210** [comment]
The method of mounting probably changes things, as I am using rclone to mount a cloud drive, not a network share. This is what the program calls instead of the drive letter and seemingly fails. You can see it calling the normal drive letters but it decides for some reason to use the NT Device Name to try to refer to the rclone mounted drive letter

![image](https://user-images.githubusercontent.com/1053504/149688370-fc472391-524f-4903-8863-a82b5c5f7ffc.png)

**Comment by pearlxcore** [comment]
https://github.com/pearlxcore/PS4-PKG-Tool/issues/16#issuecomment-711152544
