### ISSUE TITLE
Program skip PKG scanning in root directory

### ISSUE THREAD

**Issue by pearlxcore** [pearlxcore/PS4-PKG-Tool#40]

**Comment by uipipipe** [comment]
V1.5 still skipping PKG scanning in root directories

**Comment by endlessAG** [comment]
It is skipping pkg scanning in root and also, include sub folder doesnt make any difference.

**Comment by Masamune3210** [comment]
If you happen to have something reading or writing to a file in that directory, the program will also ignore it regardless of location. E.g. copying a file to or from the directory or having another tool hold a lock on one of the files in the directory
