### ISSUE TITLE
Please add LAN path

### ISSUE THREAD

**Issue by fyngd** [pearlxcore/PS4-PKG-Tool#44]
My PKG is stored on the NAS

**Comment by war3zlod3r** [comment]
I have a large repo stored on a NAS as well, you can mount the SMB share off your NAS as a network drive and this works pretty well.

**Comment by pearlxcore** [comment]
> 

I don't have a NAS to test. Can you confirm if PS4 PKG Tool is able to read PKG files from a NAS?

**Comment by war3zlod3r** [comment]
I’m saying it works, I mount the share as a network drive and it works as expected
