### ISSUE TITLE
Extract images/icons missing files

### ISSUE THREAD

**Issue by liujunhao** [pearlxcore/PS4-PKG-Tool#48]
hi pearlxcore,
if you load several pkg files with ps4-pkg-tool, use extract images/icons, it will missing some files. For example:
i extract images/icons  for diable 3, diable 3 upd, diable 3 dlc，three pkg files, i got only two  images/icons folders,  it contains diable 3 upd, diable 3 dlc.   diable 3 icon is missing. could you help to check and update, thanks a lot!

**Comment by pearlxcore** [comment]
Will check it later
