### ISSUE TITLE
Rename option for "Longname"

### ISSUE THREAD

**Issue by krugdenis** [pearlxcore/PS4-PKG-Tool#5]
Please, add an option for renaming files to "longname" content-id.
It's imposible to rename both game and patch with content-id option.
"Longname" looks like "EP4001-CUSA12747_00-DIRTRALLY2EU0001-A0116-V0100"
Content-id is shorter and applies to both game and update files.

**Comment by pearlxcore** [comment]
> Please, add an option for renaming files to "longname" content-id.
> 
> It's imposible to rename both game and patch with content-id option.
> 
> "Longname" looks like "EP4001-CUSA12747_00-DIRTRALLY2EU0001-A0116-V0100"
> 
> Content-id is shorter and applies to both game and update files.

Not sure what 'A0116' and 'V0100' value are

**Comment by krugdenis** [comment]
> > Please, add an option for renaming files to "longname" content-id.
> > It's imposible to rename both game and patch with content-id option.
> > "Longname" looks like "EP4001-CUSA12747_00-DIRTRALLY2EU0001-A0116-V0100"
> > Content-id is shorter and applies to both game and update files.
> 
> @krugdenis not sure what 'A0116' and 'V0100' value are

It's naming in PS4PKGViewer by LeecherMan, A0116 is version number (patch or game)
