### ISSUE TITLE
No packages found

### ISSUE THREAD

**Issue by JPi1872** [pearlxcore/PS4-PKG-Tool#53]
Latest version used.
Hard disk seagate 16 TB 

Getting this error message, unclear why.

29/12/2022 12:59:07 : Selected directory : 
29/12/2022 12:59:07 : G:\A
29/12/2022 12:59:07 : Creating working directory..
29/12/2022 12:59:07 : Extracting resources..
29/12/2022 12:59:09 : Checking Node.js and server module..
29/12/2022 12:59:10 : Node.js not installed.
29/12/2022 12:59:10 : Module not installed.
29/12/2022 12:59:10 : Scanning PKG..
29/12/2022 12:59:14 : Extracting PKG background music..
29/12/2022 12:59:14 : Checking hardisk free space..
29/12/2022 12:59:14 : An error occured while getting hardisk freespace : The device is not ready.

Any workaround for me? They are of course many files on the HDD. 

Disk is working fine (is new), no know issues.
Volume Serial Number is 0007-DA84
Windows is verifying files and folders...
Volume label is Seagate Hub.
File and folder verification is complete.

Windows has scanned the file system and found no problems.
No further action is required.

2740508672 KB total disk space.
 343283712 KB in 319 files.
     46336 KB in 181 indexes.
         0 KB in bad sectors
      7936 KB in use by the system.
2397170688 KB available on disk.

    262144 bytes in each allocation unit.
  61036760 total allocation units on disk.
  59695596 allocation units available on disk.

**Comment by pearlxcore** [comment]
I don't have hardisk more than 4TB so I'm unable to check whether the program support bigger hardisk or not.

**Comment by pearlxcore** [comment]
Also I think for a temporary solution try add separate folder on the PKG location list.

**Comment by Masamune3210** [comment]
> I don't have hardisk more than 4TB so I'm unable to check whether the program support bigger hardisk or not.

2740508672 KB is roughly 3TB, so you shouldn't need more than a 4TB

**Comment by pearlxcore** [comment]
You said it was 16TB

> Latest version used.
Hard disk seagate 16 TB

**Comment by Masamune3210** [comment]
I'm not OP, so idk, but 
2740508672 KB total disk space.
is not 16 TB


![image](https://github.com/pearlxcore/PS4-PKG-Tool/assets/1053504/396ea81f-722a-4594-94b5-9ee80723816e)
