### ISSUE TITLE
The version of sc.exe is either missing or invalid

### ISSUE THREAD

**Issue by Masamune3210** [pearlxcore/PS4-PKG-Tool#61]
I put orbis-pub-cmd.exe and sc.exe in PS4PKGToolTemp, but the program keeps complaining that sc.exe is either missing or invalid.

**Comment by pearlxcore** [comment]
![image](https://github.com/pearlxcore/PS4-PKG-Tool/assets/36906814/6af8e07d-756c-4b88-84f0-ae6cbcb03efe)
![image](https://github.com/pearlxcore/PS4-PKG-Tool/assets/36906814/843020f9-ee5e-41e8-8b1e-d2800c3064c3)

orbis-pub-cmd.exe related files must be in 'ext' folder

**Comment by Masamune3210** [comment]
Thanks for the heads up. Didn't see that documented anywhere

**Comment by Masamune3210** [comment]
Worked just fine for me, hence why I closed it.
