### ISSUE TITLE
software crash

### ISSUE THREAD

**Issue by Constantine-HD** [pearlxcore/PS4-PKG-Tool#9]
hi

i have 12.000 PKG file in my archive and when open it with you tools after 10sec  tool get crash and close...can you fix it 
can add extract icon in original game folder to your tools

**Comment by pearlxcore** [comment]
I don't know what causing the program crash on your pc. But i added appcenter tool so i can monitor user experience on ps4 pkg tool included error and crash. This will available on next program update v1.2.
